remove packages already upstream

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,43 +27,43 @@ jobs:
           fi
           echo "changed=$CHANGED"
           echo "changed=$CHANGED" >> "$GITHUB_OUTPUT"
-  mesa:
-    name: build mesa overlay packages
-    runs-on: ubuntu-24.04
-    needs: [changed]
-    steps:
-      - name: Check out the repo
-        if: contains(needs.changed.outputs.output1, 'mesa')
-        uses: actions/checkout@v2
-      - name: Display runner UID and GID
-        run: |
-          echo "Runner UID: $(id -u)"
-          echo "Runner GID: $(id -g)"
-        id: get_ids
-      - name: Run the build process with Docker
-        if: contains(needs.changed.outputs.output1, 'mesa')
-        uses: addnab/docker-run-action@v3
-        with:
-          image: josdehaes/asahi-alarm-pkgbuild-mesa:latest
-          options: >
-            -v ${{ github.workspace }}:/home/user/PKGBUILDs --user 1001:116
-
-          run: |
-            echo "update alarm packages"
-            sudo pacman -Syu --noconfirm
-            cd mesa && makepkg -sC --noconfirm
-      - name: Upload build artifacts
-        if: contains(needs.changed.outputs.output1, 'mesa')
-        uses: actions/upload-artifact@v4
-        with:
-          name: overlays
-          path: |
-            mesa/mesa-fex-emu-overlay-i386*
-            mesa/mesa-fex-emu-overlay-x86_64*
+  # mesa:
+  #   name: build mesa overlay packages
+  #   runs-on: ubuntu-24.04
+  #   needs: [changed]
+  #   steps:
+  #     - name: Check out the repo
+  #       if: contains(needs.changed.outputs.output1, 'mesa')
+  #       uses: actions/checkout@v2
+  #     - name: Display runner UID and GID
+  #       run: |
+  #         echo "Runner UID: $(id -u)"
+  #         echo "Runner GID: $(id -g)"
+  #       id: get_ids
+  #     - name: Run the build process with Docker
+  #       if: contains(needs.changed.outputs.output1, 'mesa')
+  #       uses: addnab/docker-run-action@v3
+  #       with:
+  #         image: josdehaes/asahi-alarm-pkgbuild-mesa:latest
+  #         options: >
+  #           -v ${{ github.workspace }}:/home/user/PKGBUILDs --user 1001:116
+  #
+  #         run: |
+  #           echo "update alarm packages"
+  #           sudo pacman -Syu --noconfirm
+  #           cd mesa && makepkg -sC --noconfirm
+  #     - name: Upload build artifacts
+  #       if: contains(needs.changed.outputs.output1, 'mesa')
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: overlays
+  #         path: |
+  #           mesa/mesa-fex-emu-overlay-i386*
+  #           mesa/mesa-fex-emu-overlay-x86_64*
   compile:
     name: building ${{ needs.changed.outputs.output1 }}
     runs-on: ubuntu-24.04-arm
-    needs: [changed, mesa]
+    needs: [changed]
     steps:
       - name: Check out the repo
         if: needs.changed.outputs.output1 != ''
@@ -73,41 +73,42 @@ jobs:
           echo "Runner UID: $(id -u)"
           echo "Runner GID: $(id -g)"
         id: get_ids
-      - name: download overlays
-        if: needs.changed.outputs.output1 != ''
-        uses: actions/download-artifact@v4
-        continue-on-error: true
-        with:
-          name: overlays
-          path: overlays
+      # - name: download overlays
+      #   if: needs.changed.outputs.output1 != ''
+      #   uses: actions/download-artifact@v4
+      #   continue-on-error: true
+      #   with:
+      #     name: overlays
+      #     path: overlays
       - name: building ${{ needs.changed.outputs.output1 }}
         if: needs.changed.outputs.output1 != ''
         uses: addnab/docker-run-action@v3
         with:
-          image: josdehaes/asahi-alarm-pkgbuild:latest
+          image: josdehaes/asahi-alarm-pkgbuild:archport
           options: >
             -v ${{ github.workspace }}:/home/user/PKGBUILDs --user 1001:116 -e B64=${{ secrets.B64 }} -e GPG_PASSPHRASE=${{ secrets.GPG_PASSPHRASE }} -e GH_TOKEN=${{ secrets.GH_TOKEN }}
 
           run: |
             set -e
+            RELEASE=archport
             CHANGED="${{ needs.changed.outputs.output1 }}"
             echo "changed=$CHANGED"
             if [ -n "$CHANGED" ]; then
               echo "import GPG key"
               printf "%s" "$B64" | base64 -d | gpg --batch --no-tty --import
-              echo "update alarm packages"
+              echo "update upstream packages"
               sudo pacman -Syu --noconfirm
-              echo "mesa x86 overlays"
-              ls overlays || true
+              # echo "mesa x86 overlays"
+              # ls overlays || true
               if [ ! -d packages ]; then
                 mkdir packages
               fi
               # import gpg key to build xkeyboard-config - this can be removed once we don't include
               # it ourselves anymore
-              gpg --recv-keys 0661D98FC933A145
+              # gpg --recv-keys 0661D98FC933A145
               cd packages
               echo "download current release databases"
-              gh release download aarch64 --repo asahi-alarm/asahi-alarm --pattern asahi-alarm.db* --pattern asahi-alarm.files*
+              gh release download $RELEASE --repo asahi-alarm/asahi-alarm --pattern asahi-alarm.db* --pattern asahi-alarm.files*
               TO_REMOVE=()
               cd ..
               echo "starting build"
@@ -141,27 +142,27 @@ jobs:
                 # fetch filenames of previous versions of this package so we can remove them from
                 # the release later. Note this will contain the package file and the signature file
                 BASE=$(echo $out | sed 's/\([a-z-]*\)-[0-9].*/\1/')
-                TO_REMOVE+="$(gh release view aarch64 --repo asahi-alarm/asahi-alarm | grep "${BASE}-" | awk '{ print $2 }') "
+                TO_REMOVE+="$(gh release view $RELEASE --repo asahi-alarm/asahi-alarm | grep "${BASE}-" | awk '{ print $2 }') "
                 echo "uploading $out"
-                gh release upload aarch64 --repo asahi-alarm/asahi-alarm --clobber "$out" "${out}.sig"
+                gh release upload $RELEASE --repo asahi-alarm/asahi-alarm --clobber "$out" "${out}.sig"
               done
               echo "uploading database files"
-              gh release upload aarch64 --repo asahi-alarm/asahi-alarm --clobber asahi-alarm.db* asahi-alarm.files*
+              gh release upload $RELEASE --repo asahi-alarm/asahi-alarm --clobber asahi-alarm.db* asahi-alarm.files*
               # once the database files are uploaded, we can remove the old versions
               for old in $TO_REMOVE; do
                 # first check if we this is not a package we just uploaded
                 if [ ! -f "$old" ]; then
                   echo "removing $old from release"
-                  gh release delete-asset aarch64 --repo asahi-alarm/asahi-alarm -y $old || true
+                  gh release delete-asset $RELEASE --repo asahi-alarm/asahi-alarm -y $old || true
                 fi
               done
               ls
             else
               echo "nothing to build"
             fi
-      - name: delete build artifacts
-        uses: geekyeggo/delete-artifact@v5
-        continue-on-error: true
-        with:
-          name: overlays
-          failOnError: false
+    # - name: delete build artifacts
+    #   uses: geekyeggo/delete-artifact@v5
+    #   continue-on-error: true
+    #   with:
+    #     name: overlays
+    #     failOnError: false
